//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppPaper.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int MaterialID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
